import { Vehicle, Review, NewsArticle } from "./types";

export const vehicles: Vehicle[] = [
  {
    id: "v2",
    slug: "audi-a4-avant-40-tdi-s-line-2021",
    make: "Audi",
    model: "A4",
    variant: "Avant 40 TDI S Line",
    year: 2021,
    price: 21495,
    monthlyFinance: 339,
    mileage: 27100,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Estate",
    colour: "Glacier White",
    engineSize: "2.0L",
    doors: 5,
    seats: 5,
    registration: "AX21 NNX",
    mot: { expiry: "2027-01-09", status: "Valid" },
    owners: 2,
    ulez: true,
    status: "In Stock",
    featured: true,
    description:
      "Practical S Line Avant with class-leading boot space, virtual cockpit, and Audi's composed ride. Ideal for families who still want a premium feel behind the wheel.",
    features: [
      "S Line exterior styling",
      "Virtual Cockpit digital dash",
      "Panoramic sunroof",
      "Bang & Olufsen sound system",
      "Matrix LED headlights",
      "Electric tailgate",
      "Heated front seats",
    ],
    history: [
      { label: "Full service history", detail: "Two Audi dealer stamps, last service at 25,600 miles" },
      { label: "2 registered keepers", detail: "Private ownership throughout" },
      { label: "MOT", detail: "Valid until January 2027" },
    ],
    silhouetteSeed: 2,
    createdAt: "2026-06-20",
    images: ["/vehicles/shared/new-arrival-coming-soon.png"],
  },
  {
    id: "v3",
    slug: "mercedes-e220d-se-2016",
    make: "Mercedes-Benz",
    model: "E-Class",
    variant: "E220d SE Auto",
    year: 2016,
    price: 7800,
    monthlyFinance: 122,
    mileage: 160771,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Saloon",
    colour: "Silver",
    engineSize: "1,950cc",
    doors: 4,
    seats: 5,
    registration: "ND66 LWU",
    mot: { expiry: "2027-04-03", status: "Valid" },
    owners: 2,
    ulez: true,
    status: "Just Arrived",
    featured: true,
    power: "191 BHP",
    cylinders: 4,
    engineType: "Turbocharged",
    topSpeed: "149 mph",
    fuelTankCapacity: "66 litres",
    valvesPerCylinder: 4,
    euroStatus: "Euro 6",
    description:
      "This E220d SE Auto comes from the first year of the W213-generation E-Class — one of Mercedes-Benz's most significant redesigns of the model, introducing an entirely new cabin and the 2.0-litre turbodiesel engine that replaced the previous generation's 2.1-litre unit. It produces 191bhp and drives through Mercedes' smooth-shifting 9-speed automatic gearbox. Finished in Silver, this example has had two registered keepers and has covered 160,771 miles, with an MOT valid until 3 April 2027. SE specification brings keyless start, heated seats with leather upholstery, and the E-Class's digital instrument display as standard — a refined, quiet motorway cruiser at a used-diesel price point.",
    features: [
      "12.3-inch digital instrument cluster",
      "Heated front seats with leather upholstery",
      "KEYLESS-GO keyless start",
      "DAB digital radio",
      "Multifunction steering wheel with Bluetooth & audio controls",
      "Automatic climate control",
      "Cruise control",
      "LED daytime running lights",
      "Alloy wheels",
    ],
    history: [
      { label: "2 registered keepers", detail: "This vehicle has had two owners from new" },
      { label: "MOT", detail: "Valid until 3 April 2027" },
    ],
    images: [
      "/vehicles/mercedes-e220d-se-2016/3-front.jpg",
      "/vehicles/mercedes-e220d-se-2016/2-front-three-quarter.jpg",
      "/vehicles/mercedes-e220d-se-2016/6-front-three-quarter-alt.jpg",
      "/vehicles/mercedes-e220d-se-2016/1-side.jpg",
      "/vehicles/mercedes-e220d-se-2016/5-side-detail.jpg",
      "/vehicles/mercedes-e220d-se-2016/4-rear.jpg",
      "/vehicles/mercedes-e220d-se-2016/7-interior-dash.jpg",
      "/vehicles/mercedes-e220d-se-2016/8-interior-rear-seats.jpg",
      "/vehicles/mercedes-e220d-se-2016/9-interior-odometer.jpg",
    ],
    silhouetteSeed: 3,
    createdAt: "2026-07-08",
  },
  {
    id: "v4",
    slug: "range-rover-evoque-r-dynamic-2021",
    make: "Land Rover",
    model: "Range Rover Evoque",
    variant: "R-Dynamic S D165",
    year: 2021,
    price: 27995,
    monthlyFinance: 435,
    mileage: 22300,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    colour: "Santorini Black",
    engineSize: "2.0L",
    doors: 5,
    seats: 5,
    registration: "AX21 NNY",
    mot: { expiry: "2026-12-11", status: "Valid" },
    owners: 2,
    ulez: true,
    status: "In Stock",
    featured: true,
    description:
      "Head-turning Evoque R-Dynamic with commanding road presence and a beautifully kept cabin. A genuine one-of-a-kind spec on the forecourt right now.",
    features: [
      "R-Dynamic body kit",
      "Pixel-laser LED headlights",
      "Meridian sound system",
      "360° parking camera",
      "Heated steering wheel",
      "Air suspension",
    ],
    history: [
      { label: "Full service history", detail: "Land Rover approved dealer history" },
      { label: "2 registered keepers", detail: "No recorded accident damage" },
      { label: "MOT", detail: "Valid until December 2026" },
    ],
    silhouetteSeed: 4,
    createdAt: "2026-06-02",
    images: ["/vehicles/shared/new-arrival-coming-soon.png"],
  },
  {
    id: "v8",
    slug: "vauxhall-astra-sri-2017",
    make: "Vauxhall",
    model: "Astra",
    variant: "SRi",
    year: 2017,
    price: 4800,
    monthlyFinance: 75,
    mileage: 5100,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Estate",
    colour: "Silver",
    engineSize: "1,399cc",
    doors: 4,
    seats: 5,
    registration: "CX67 GDK",
    mot: { expiry: "2026-12-15", status: "Valid" },
    owners: 1,
    ulez: true,
    status: "Just Arrived",
    featured: true,
    power: "148 BHP",
    cylinders: 4,
    engineType: "Turbocharged",
    topSpeed: "134 mph",
    fuelTankCapacity: "48 litres",
    euroStatus: "Euro 6",
    description:
      "This SRi Sports Tourer pairs Vauxhall's 148bhp 1.4-litre turbo petrol engine with a 6-speed manual gearbox, plus the SRi's sportier suspension setup and alloy wheels for sharper handling than the standard Astra. Finished in Silver with one registered keeper from new, this example has covered just 5,100 miles and comes with an MOT valid until 15 December 2026.",
    features: [
      "Sports-tuned suspension & alloy wheels",
      "Front fog lights",
      "Cruise control with speed limiter",
      "Touchscreen with DAB radio, Bluetooth & USB",
      "Leather-trimmed steering wheel & gearstick",
      "Air conditioning",
    ],
    history: [
      { label: "1 registered keeper", detail: "This vehicle has had one owner from new" },
      { label: "MOT", detail: "Valid until 15 December 2026" },
    ],
    images: [
      "/vehicles/vauxhall-astra-sri-2017/1-front.jpg",
      "/vehicles/vauxhall-astra-sri-2017/2-front-three-quarter.jpg",
      "/vehicles/vauxhall-astra-sri-2017/3-front-three-quarter-alt.jpg",
      "/vehicles/vauxhall-astra-sri-2017/4-side.jpg",
      "/vehicles/vauxhall-astra-sri-2017/5-side-alt.jpg",
      "/vehicles/vauxhall-astra-sri-2017/6-rear-three-quarter.jpg",
      "/vehicles/vauxhall-astra-sri-2017/7-rear-three-quarter-alt.jpg",
      "/vehicles/vauxhall-astra-sri-2017/8-rear.jpg",
      "/vehicles/vauxhall-astra-sri-2017/9-boot.jpg",
      "/vehicles/vauxhall-astra-sri-2017/10-interior-dash.jpg",
      "/vehicles/vauxhall-astra-sri-2017/11-interior-console.jpg",
    ],
    silhouetteSeed: 7,
    createdAt: "2026-03-22",
  },
  {
    id: "v11",
    slug: "mercedes-s350d-l-amg-line-2018",
    make: "Mercedes-Benz",
    model: "S-Class",
    variant: "S 350 d L AMG Line Executive Auto",
    year: 2018,
    price: 15000,
    monthlyFinance: 234,
    mileage: 173716,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Saloon",
    colour: "Black",
    engineSize: "2,925cc",
    doors: 4,
    seats: 5,
    registration: "R500 UMR",
    mot: { expiry: "2026-09-19", status: "Valid" },
    owners: 1,
    ulez: true,
    status: "Just Arrived",
    featured: true,
    power: "282 BHP",
    cylinders: 6,
    engineType: "Turbocharged",
    topSpeed: "155 mph",
    fuelTankCapacity: "70 litres",
    euroStatus: "Euro 6c",
    description:
      "This S 350 d L AMG Line Executive brings the long-wheelbase W222 S-Class's flagship diesel powertrain — a 2.9-litre straight-six turbodiesel producing 282bhp through Mercedes' 9-speed automatic gearbox — paired with AMG Line styling and the extended rear legroom of the L bodystyle. Finished in Black with one registered keeper from new, this example has covered 173,716 miles and comes with an MOT valid until 19 September 2026.",
    features: [
      "AMG Line styling & alloy wheels",
      "Widescreen COMAND infotainment display",
      "Leather upholstery",
      "Rear seat comfort headrests",
      "Ambient interior lighting",
      "Long-wheelbase (L) body for extended rear legroom",
    ],
    history: [
      { label: "1 registered keeper", detail: "This vehicle has had one owner from new" },
      { label: "MOT", detail: "Valid until 19 September 2026" },
    ],
    images: [
      "/vehicles/mercedes-s350d-l-amg-line-2018/1-front.jpg",
      "/vehicles/mercedes-s350d-l-amg-line-2018/2-front-three-quarter.jpg",
      "/vehicles/mercedes-s350d-l-amg-line-2018/3-side.jpg",
      "/vehicles/mercedes-s350d-l-amg-line-2018/4-wheel-detail.jpg",
      "/vehicles/mercedes-s350d-l-amg-line-2018/5-rear-three-quarter.jpg",
      "/vehicles/mercedes-s350d-l-amg-line-2018/6-interior-dash.jpg",
      "/vehicles/mercedes-s350d-l-amg-line-2018/7-interior-seats.jpg",
    ],
    silhouetteSeed: 11,
    createdAt: "2026-06-15",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    name: "Daniel Whitmore",
    rating: 5,
    date: "2026-06-28",
    vehicle: "BMW 3 Series",
    text: "Genuinely the easiest car purchase I've made. No pressure, straight answers, and the car was exactly as described. Would go back in a heartbeat.",
  },
  {
    id: "r2",
    name: "Priya Anand",
    rating: 5,
    date: "2026-06-19",
    vehicle: "Audi Q5",
    text: "Part-exchanged my old car and the valuation was fair from the start. The whole process took under an hour on collection day.",
  },
  {
    id: "r3",
    name: "Callum Reid",
    rating: 5,
    date: "2026-06-02",
    vehicle: "Tesla Model 3",
    text: "First time buying an EV and the team talked me through everything, charging included. Car has been faultless since.",
  },
  {
    id: "r4",
    name: "Harriet Osei",
    rating: 4,
    date: "2026-05-21",
    vehicle: "MINI Cooper",
    text: "Lovely little car, exactly as pictured. Only reason for 4 stars is I had to wait a few extra days for the service history paperwork.",
  },
  {
    id: "r5",
    name: "Mohammed Iqbal",
    rating: 5,
    date: "2026-05-10",
    vehicle: "Skoda Octavia",
    text: "Finance was sorted same day, monthly payment matched the online calculator exactly. No surprises, no hidden fees.",
  },
  {
    id: "r6",
    name: "Sophie Vance",
    rating: 5,
    date: "2026-04-27",
    vehicle: "Mercedes A-Class",
    text: "Second car I've bought from Annax now. Consistently honest about mileage, condition, and history. That trust is worth a lot.",
  },
];

export const news: NewsArticle[] = [
  {
    id: "n1",
    slug: "annax-summer-stock-update-2026",
    title: "Fresh Summer Arrivals Across the Forecourt",
    excerpt:
      "We've added a run of low-mileage saloons and estates this month, including a one-owner C220d AMG Line and a Long Range Tesla Model 3.",
    date: "2026-07-10",
    category: "Stock Update",
  },
  {
    id: "n2",
    slug: "buying-an-ev-what-to-know",
    title: "Buying Your First EV: What Actually Matters",
    excerpt:
      "Range anxiety, home charging, and running costs — we break down what to genuinely consider before switching to electric.",
    date: "2026-06-24",
    category: "Buyer's Guide",
  },
  {
    id: "n3",
    slug: "part-exchange-getting-a-fair-price",
    title: "How We Value Your Part Exchange Fairly",
    excerpt:
      "A look inside our valuation process — what pushes your part-exchange price up, and what to fix before you bring the car in.",
    date: "2026-06-05",
    category: "Advice",
  },
];
