import { Vehicle, Review, NewsArticle } from "./types";

export const vehicles: Vehicle[] = [
  {
    id: "v1",
    slug: "bmw-3-series-320d-m-sport-2022",
    make: "BMW",
    model: "3 Series",
    variant: "320d M Sport",
    year: 2022,
    price: 24995,
    monthlyFinance: 389,
    mileage: 18400,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Saloon",
    colour: "Mineral Grey",
    engineSize: "2.0L",
    doors: 4,
    seats: 5,
    registration: "AX22 NNX",
    mot: { expiry: "2027-03-14", status: "Valid" },
    owners: 1,
    ulez: true,
    status: "In Stock",
    featured: true,
    description:
      "A one-owner 320d M Sport finished in Mineral Grey with the full BMW service history. Comfortable, quiet on the motorway, and returns strong economy for a car with this much presence.",
    features: [
      "M Sport styling package",
      "Heated leather seats",
      "Live Cockpit Professional",
      "Reverse camera",
      "Adaptive LED headlights",
      "Wireless Apple CarPlay",
      "Keyless entry",
      "Parking sensors front & rear",
    ],
    history: [
      { label: "Full service history", detail: "Serviced at BMW main dealer, last service at 17,200 miles" },
      { label: "1 registered keeper", detail: "Company owned, no accident history recorded" },
      { label: "MOT", detail: "Valid until March 2027" },
    ],
    silhouetteSeed: 1,
    createdAt: "2026-07-01",
  },
  {
    id: "v2",
    slug: "audi-a4-avant-40-tdi-s-line-2021",
    make: "Audi",
    model: "A4",
    variant: "Avant 40 TDI S Line",
    year: 2021,
    price: 21495,
    monthlyFinance: 339,
    mileage: 27100,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Estate",
    colour: "Glacier White",
    engineSize: "2.0L",
    doors: 5,
    seats: 5,
    registration: "AX21 NNX",
    mot: { expiry: "2027-01-09", status: "Valid" },
    owners: 2,
    ulez: true,
    status: "In Stock",
    featured: true,
    description:
      "Practical S Line Avant with class-leading boot space, virtual cockpit, and Audi's composed ride. Ideal for families who still want a premium feel behind the wheel.",
    features: [
      "S Line exterior styling",
      "Virtual Cockpit digital dash",
      "Panoramic sunroof",
      "Bang & Olufsen sound system",
      "Matrix LED headlights",
      "Electric tailgate",
      "Heated front seats",
    ],
    history: [
      { label: "Full service history", detail: "Two Audi dealer stamps, last service at 25,600 miles" },
      { label: "2 registered keepers", detail: "Private ownership throughout" },
      { label: "MOT", detail: "Valid until January 2027" },
    ],
    silhouetteSeed: 2,
    createdAt: "2026-06-20",
  },
  {
    id: "v3",
    slug: "mercedes-e220d-se-2016",
    make: "Mercedes-Benz",
    model: "E-Class",
    variant: "E220d SE Auto",
    year: 2016,
    price: 7800,
    monthlyFinance: 122,
    mileage: 160771,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Saloon",
    colour: "Silver",
    engineSize: "1,950cc",
    doors: 4,
    seats: 5,
    registration: "ND66 LWU",
    mot: { expiry: "2027-04-03", status: "Valid" },
    owners: 2,
    ulez: true,
    status: "Just Arrived",
    featured: true,
    power: "191 BHP",
    cylinders: 4,
    engineType: "Turbocharged",
    topSpeed: "149 mph",
    fuelTankCapacity: "66 litres",
    valvesPerCylinder: 4,
    euroStatus: "Euro 6",
    description:
      "This E220d SE Auto comes from the first year of the W213-generation E-Class — one of Mercedes-Benz's most significant redesigns of the model, introducing an entirely new cabin and the 2.0-litre turbodiesel engine that replaced the previous generation's 2.1-litre unit. It produces 191bhp and drives through Mercedes' smooth-shifting 9-speed automatic gearbox. Finished in Silver, this example has had two registered keepers and has covered 160,771 miles, with an MOT valid until 3 April 2027. SE specification brings keyless start, heated seats with leather upholstery, and the E-Class's digital instrument display as standard — a refined, quiet motorway cruiser at a used-diesel price point.",
    features: [
      "12.3-inch digital instrument cluster",
      "Heated front seats with leather upholstery",
      "KEYLESS-GO keyless start",
      "DAB digital radio",
      "Multifunction steering wheel with Bluetooth & audio controls",
      "Automatic climate control",
      "Cruise control",
      "LED daytime running lights",
      "Alloy wheels",
    ],
    history: [
      { label: "2 registered keepers", detail: "This vehicle has had two owners from new" },
      { label: "MOT", detail: "Valid until 3 April 2027" },
    ],
    images: [
      "/vehicles/mercedes-e220d-se-2016/3-front.jpg",
      "/vehicles/mercedes-e220d-se-2016/2-front-three-quarter.jpg",
      "/vehicles/mercedes-e220d-se-2016/6-front-three-quarter-alt.jpg",
      "/vehicles/mercedes-e220d-se-2016/1-side.jpg",
      "/vehicles/mercedes-e220d-se-2016/5-side-detail.jpg",
      "/vehicles/mercedes-e220d-se-2016/4-rear.jpg",
      "/vehicles/mercedes-e220d-se-2016/7-interior-dash.jpg",
      "/vehicles/mercedes-e220d-se-2016/8-interior-rear-seats.jpg",
      "/vehicles/mercedes-e220d-se-2016/9-interior-odometer.jpg",
    ],
    silhouetteSeed: 3,
    createdAt: "2026-07-08",
  },
  {
    id: "v4",
    slug: "range-rover-evoque-r-dynamic-2021",
    make: "Land Rover",
    model: "Range Rover Evoque",
    variant: "R-Dynamic S D165",
    year: 2021,
    price: 27995,
    monthlyFinance: 435,
    mileage: 22300,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    colour: "Santorini Black",
    engineSize: "2.0L",
    doors: 5,
    seats: 5,
    registration: "AX21 NNY",
    mot: { expiry: "2026-12-11", status: "Valid" },
    owners: 2,
    ulez: true,
    status: "In Stock",
    featured: true,
    description:
      "Head-turning Evoque R-Dynamic with commanding road presence and a beautifully kept cabin. A genuine one-of-a-kind spec on the forecourt right now.",
    features: [
      "R-Dynamic body kit",
      "Pixel-laser LED headlights",
      "Meridian sound system",
      "360° parking camera",
      "Heated steering wheel",
      "Air suspension",
    ],
    history: [
      { label: "Full service history", detail: "Land Rover approved dealer history" },
      { label: "2 registered keepers", detail: "No recorded accident damage" },
      { label: "MOT", detail: "Valid until December 2026" },
    ],
    silhouetteSeed: 4,
    createdAt: "2026-06-02",
  },
  {
    id: "v5",
    slug: "volkswagen-golf-gtd-2020",
    make: "Volkswagen",
    model: "Golf",
    variant: "GTD 2.0 TDI",
    year: 2020,
    price: 18495,
    monthlyFinance: 289,
    mileage: 31500,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Hatchback",
    colour: "Deep Black Pearl",
    engineSize: "2.0L",
    doors: 5,
    seats: 5,
    registration: "AX20 NNX",
    mot: { expiry: "2026-11-18", status: "Valid" },
    owners: 3,
    ulez: true,
    status: "In Stock",
    featured: false,
    description:
      "The GTD blends hot-hatch driving thrills with genuine diesel economy. Sharp, tidy, and ready to be enjoyed on the school run or the back roads.",
    features: [
      "GTD sports suspension",
      "Progressive steering",
      "Digital cockpit",
      "Adaptive cruise control",
      "Climate control",
    ],
    history: [
      { label: "Full service history", detail: "VW dealer and specialist stamps" },
      { label: "3 registered keepers", detail: "Enthusiast owned, no modifications" },
      { label: "MOT", detail: "Valid until November 2026" },
    ],
    silhouetteSeed: 5,
    createdAt: "2026-05-14",
  },
  {
    id: "v6",
    slug: "mini-cooper-s-2021",
    make: "MINI",
    model: "Cooper",
    variant: "S Sport",
    year: 2021,
    price: 16995,
    monthlyFinance: 265,
    mileage: 19800,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Hatchback",
    colour: "British Racing Green",
    engineSize: "2.0L",
    doors: 3,
    seats: 4,
    registration: "AX21 NNZ",
    mot: { expiry: "2027-02-27", status: "Valid" },
    owners: 1,
    ulez: true,
    status: "In Stock",
    featured: false,
    description:
      "Cheeky, characterful, and quick — this Cooper S wears British Racing Green beautifully and drives exactly how a MINI should.",
    features: [
      "Sport seats",
      "Union Jack LED tail lights",
      "Harman Kardon sound system",
      "Head-up display",
      "Comfort access",
    ],
    history: [
      { label: "Full service history", detail: "MINI dealer serviced from new" },
      { label: "1 registered keeper", detail: "Private ownership, garaged" },
      { label: "MOT", detail: "Valid until February 2027" },
    ],
    silhouetteSeed: 6,
    createdAt: "2026-04-30",
  },
  {
    id: "v7",
    slug: "audi-q5-45-tfsi-s-line-2020",
    make: "Audi",
    model: "Q5",
    variant: "45 TFSI S Line Quattro",
    year: 2020,
    price: 25995,
    monthlyFinance: 405,
    mileage: 29600,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    colour: "Navarra Blue",
    engineSize: "2.0L",
    doors: 5,
    seats: 5,
    registration: "AX20 NNY",
    mot: { expiry: "2026-10-05", status: "Due Soon" },
    owners: 2,
    ulez: true,
    status: "In Stock",
    featured: false,
    description:
      "Quattro all-wheel drive confidence in a handsome Navarra Blue Q5. A genuinely capable family SUV that never feels like hard work to drive.",
    features: [
      "Quattro all-wheel drive",
      "S Line body kit",
      "Virtual Cockpit",
      "Panoramic sunroof",
      "Power tailgate",
    ],
    history: [
      { label: "Full service history", detail: "Audi dealer serviced" },
      { label: "2 registered keepers", detail: "No accident history recorded" },
      { label: "MOT", detail: "Due October 2026 — fresh MOT provided on sale" },
    ],
    silhouetteSeed: 7,
    createdAt: "2026-03-22",
  },
  {
    id: "v8",
    slug: "vauxhall-astra-sri-2017",
    make: "Vauxhall",
    model: "Astra",
    variant: "SRi",
    year: 2017,
    price: 4800,
    monthlyFinance: 75,
    mileage: 5100,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Estate",
    colour: "Silver",
    engineSize: "1,399cc",
    doors: 4,
    seats: 5,
    registration: "CX67 GDK",
    mot: { expiry: "2026-12-15", status: "Valid" },
    owners: 1,
    ulez: true,
    status: "Just Arrived",
    featured: true,
    power: "148 BHP",
    cylinders: 4,
    engineType: "Turbocharged",
    topSpeed: "134 mph",
    fuelTankCapacity: "48 litres",
    euroStatus: "Euro 6",
    description:
      "This SRi Sports Tourer pairs Vauxhall's 148bhp 1.4-litre turbo petrol engine with a 6-speed manual gearbox, plus the SRi's sportier suspension setup and alloy wheels for sharper handling than the standard Astra. Finished in Silver with one registered keeper from new, this example has covered just 5,100 miles and comes with an MOT valid until 15 December 2026.",
    features: [
      "Sports-tuned suspension & alloy wheels",
      "Front fog lights",
      "Cruise control with speed limiter",
      "Touchscreen with DAB radio, Bluetooth & USB",
      "Leather-trimmed steering wheel & gearstick",
      "Air conditioning",
    ],
    history: [
      { label: "1 registered keeper", detail: "This vehicle has had one owner from new" },
      { label: "MOT", detail: "Valid until 15 December 2026" },
    ],
    images: [
      "/vehicles/vauxhall-astra-sri-2017/1-front.jpg",
      "/vehicles/vauxhall-astra-sri-2017/2-front-three-quarter.jpg",
      "/vehicles/vauxhall-astra-sri-2017/3-front-three-quarter-alt.jpg",
      "/vehicles/vauxhall-astra-sri-2017/4-side.jpg",
      "/vehicles/vauxhall-astra-sri-2017/5-side-alt.jpg",
      "/vehicles/vauxhall-astra-sri-2017/6-rear-three-quarter.jpg",
      "/vehicles/vauxhall-astra-sri-2017/7-rear-three-quarter-alt.jpg",
      "/vehicles/vauxhall-astra-sri-2017/8-rear.jpg",
      "/vehicles/vauxhall-astra-sri-2017/9-boot.jpg",
      "/vehicles/vauxhall-astra-sri-2017/10-interior-dash.jpg",
      "/vehicles/vauxhall-astra-sri-2017/11-interior-console.jpg",
    ],
    silhouetteSeed: 7,
    createdAt: "2026-03-22",
  },
  {
    id: "v9",
    slug: "nissan-qashqai-tekna-2021",
    make: "Nissan",
    model: "Qashqai",
    variant: "Tekna DiG-T",
    year: 2021,
    price: 19495,
    monthlyFinance: 305,
    mileage: 23900,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    colour: "Storm White",
    engineSize: "1.3L",
    doors: 5,
    seats: 5,
    registration: "AX21 NNW",
    mot: { expiry: "2027-01-30", status: "Valid" },
    owners: 1,
    ulez: true,
    status: "In Stock",
    featured: false,
    description:
      "Top-spec Tekna trim with every box ticked — leather, panoramic roof, and Nissan's excellent ProPILOT assist for stress-free motorway miles.",
    features: [
      "ProPILOT assist",
      "Panoramic glass roof",
      "Leather heated seats",
      "Bose sound system",
      "360° around view monitor",
    ],
    history: [
      { label: "Full service history", detail: "Nissan dealer serviced" },
      { label: "1 registered keeper", detail: "Private ownership, no claims" },
      { label: "MOT", detail: "Valid until January 2027" },
    ],
    silhouetteSeed: 9,
    createdAt: "2026-05-27",
  },
  {
    id: "v10",
    slug: "skoda-octavia-vrs-2020",
    make: "Skoda",
    model: "Octavia",
    variant: "vRS TDI",
    year: 2020,
    price: 19995,
    monthlyFinance: 315,
    mileage: 34200,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Estate",
    colour: "Race Blue",
    engineSize: "2.0L",
    doors: 5,
    seats: 5,
    registration: "AX20 NNZ",
    mot: { expiry: "2026-09-16", status: "Due Soon" },
    owners: 2,
    ulez: true,
    status: "In Stock",
    featured: false,
    description:
      "The vRS estate is the enthusiast's secret weapon — huge boot, punchy diesel, and genuinely engaging handling for the money.",
    features: [
      "vRS sports suspension",
      "Virtual cockpit",
      "Canton sound system",
      "Adaptive cruise control",
      "Full LED matrix lights",
    ],
    history: [
      { label: "Full service history", detail: "Skoda dealer and specialist history" },
      { label: "2 registered keepers", detail: "No accident history recorded" },
      { label: "MOT", detail: "Due September 2026 — fresh MOT provided on sale" },
    ],
    silhouetteSeed: 10,
    createdAt: "2026-02-11",
  },
  {
    id: "v11",
    slug: "mercedes-a-class-a200-amg-line-2021",
    make: "Mercedes-Benz",
    model: "A-Class",
    variant: "A200 AMG Line",
    year: 2021,
    price: 18995,
    monthlyFinance: 297,
    mileage: 26400,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Hatchback",
    colour: "Polar White",
    engineSize: "1.3L",
    doors: 5,
    seats: 5,
    registration: "AX21 NNV",
    mot: { expiry: "2026-12-28", status: "Valid" },
    owners: 1,
    ulez: true,
    status: "In Stock",
    featured: false,
    description:
      "Sharp, tech-laden, and effortless to drive around town. The A200 AMG Line brings big-Mercedes cabin quality to a compact footprint.",
    features: [
      "MBUX with 'Hey Mercedes' voice control",
      "AMG Line styling",
      "Ambient lighting",
      "Reversing camera",
      "Wireless smartphone charging",
    ],
    history: [
      { label: "Full service history", detail: "Mercedes-Benz dealer serviced" },
      { label: "1 registered keeper", detail: "Private ownership from new" },
      { label: "MOT", detail: "Valid until December 2026" },
    ],
    silhouetteSeed: 11,
    createdAt: "2026-06-15",
  },
  {
    id: "v12",
    slug: "ford-focus-st-line-2019",
    make: "Ford",
    model: "Focus",
    variant: "ST-Line 1.5 EcoBoost",
    year: 2019,
    price: 13995,
    monthlyFinance: 219,
    mileage: 38700,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    colour: "Magnetic Grey",
    engineSize: "1.5L",
    doors: 5,
    seats: 5,
    registration: "AX19 NNX",
    mot: { expiry: "2026-08-22", status: "Due Soon" },
    owners: 3,
    ulez: true,
    status: "In Stock",
    featured: false,
    description:
      "Well-priced ST-Line with sharp handling and Ford's punchy 1.5 EcoBoost. A great value entry point into the Annax range.",
    features: [
      "ST-Line body styling",
      "SYNC 3 touchscreen",
      "Sports suspension",
      "Rear parking sensors",
      "Cruise control",
    ],
    history: [
      { label: "Full service history", detail: "Ford dealer and independent stamps" },
      { label: "3 registered keepers", detail: "No accident history recorded" },
      { label: "MOT", detail: "Due August 2026 — fresh MOT provided on sale" },
    ],
    silhouetteSeed: 12,
    createdAt: "2026-01-19",
  },
  {
    id: "v13",
    slug: "kia-picanto-vr7-2015",
    make: "Kia",
    model: "Picanto",
    variant: "VR7",
    year: 2015,
    price: 1950,
    monthlyFinance: 44,
    mileage: 96000,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    colour: "Red",
    engineSize: "1.0L",
    doors: 5,
    seats: 5,
    registration: "GF15 FBA",
    mot: { expiry: "2026-12-19", status: "Valid" },
    owners: 1,
    ulez: true,
    status: "Just Arrived",
    featured: true,
    description:
      "A practical, low-cost Kia Picanto VR7 finished in eye-catching red — an ideal first car or economical runabout. The 1.0-litre petrol engine and 5-speed manual gearbox keep fuel and insurance costs down, and this example comes with a fresh MOT to December 2026.",
    features: [
      "Alloy wheels",
      "Steering wheel-mounted audio & Bluetooth controls",
      "Front fog lights",
      "Rear privacy glass",
      "5-door practicality",
      "Low-cost 1.0L engine — cheap to insure and run",
    ],
    history: [
      { label: "1 registered keeper", detail: "First registered 31 March 2015" },
      { label: "MOT", detail: "Valid until 19 December 2026" },
    ],
    silhouetteSeed: 13,
    createdAt: "2026-07-17",
    images: [
      "/vehicles/kia-picanto-2015-vr7/1-front-three-quarter.jpg",
      "/vehicles/kia-picanto-2015-vr7/2-front.jpg",
      "/vehicles/kia-picanto-2015-vr7/3-side.jpg",
      "/vehicles/kia-picanto-2015-vr7/4-rear-three-quarter.jpg",
      "/vehicles/kia-picanto-2015-vr7/5-rear.jpg",
      "/vehicles/kia-picanto-2015-vr7/6-rear-detail.jpg",
      "/vehicles/kia-picanto-2015-vr7/7-side-detail.jpg",
      "/vehicles/kia-picanto-2015-vr7/8-interior-dash.jpg",
      "/vehicles/kia-picanto-2015-vr7/9-interior-odometer.jpg",
    ],
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    name: "Daniel Whitmore",
    rating: 5,
    date: "2026-06-28",
    vehicle: "BMW 3 Series",
    text: "Genuinely the easiest car purchase I've made. No pressure, straight answers, and the car was exactly as described. Would go back in a heartbeat.",
  },
  {
    id: "r2",
    name: "Priya Anand",
    rating: 5,
    date: "2026-06-19",
    vehicle: "Audi Q5",
    text: "Part-exchanged my old car and the valuation was fair from the start. The whole process took under an hour on collection day.",
  },
  {
    id: "r3",
    name: "Callum Reid",
    rating: 5,
    date: "2026-06-02",
    vehicle: "Tesla Model 3",
    text: "First time buying an EV and the team talked me through everything, charging included. Car has been faultless since.",
  },
  {
    id: "r4",
    name: "Harriet Osei",
    rating: 4,
    date: "2026-05-21",
    vehicle: "MINI Cooper",
    text: "Lovely little car, exactly as pictured. Only reason for 4 stars is I had to wait a few extra days for the service history paperwork.",
  },
  {
    id: "r5",
    name: "Mohammed Iqbal",
    rating: 5,
    date: "2026-05-10",
    vehicle: "Skoda Octavia",
    text: "Finance was sorted same day, monthly payment matched the online calculator exactly. No surprises, no hidden fees.",
  },
  {
    id: "r6",
    name: "Sophie Vance",
    rating: 5,
    date: "2026-04-27",
    vehicle: "Mercedes A-Class",
    text: "Second car I've bought from Annax now. Consistently honest about mileage, condition, and history. That trust is worth a lot.",
  },
];

export const news: NewsArticle[] = [
  {
    id: "n1",
    slug: "annax-summer-stock-update-2026",
    title: "Fresh Summer Arrivals Across the Forecourt",
    excerpt:
      "We've added a run of low-mileage saloons and estates this month, including a one-owner C220d AMG Line and a Long Range Tesla Model 3.",
    date: "2026-07-10",
    category: "Stock Update",
  },
  {
    id: "n2",
    slug: "buying-an-ev-what-to-know",
    title: "Buying Your First EV: What Actually Matters",
    excerpt:
      "Range anxiety, home charging, and running costs — we break down what to genuinely consider before switching to electric.",
    date: "2026-06-24",
    category: "Buyer's Guide",
  },
  {
    id: "n3",
    slug: "part-exchange-getting-a-fair-price",
    title: "How We Value Your Part Exchange Fairly",
    excerpt:
      "A look inside our valuation process — what pushes your part-exchange price up, and what to fix before you bring the car in.",
    date: "2026-06-05",
    category: "Advice",
  },
];
